# Generated by Django 5.1 on 2024-10-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0003_customerrequest_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='payment_mode',
            field=models.CharField(max_length=255),
        ),
    ]
